// start of FETCH SUSHIS
export const FETCH_SUSHIS_START = 'FETCH_SUSHIS_START'
export const FETCH_SUSHIS_SUCCESS = 'FETCH_SUSHIS_SUCCESS'
export const FETCH_SUSHIS_FAIL = 'FETCH_SUSHIS_FAIL'
// end of FETCH SUSHIS

// start of MORE BUTTON
export const MORE_BUTTON_WAS_CLICKED = 'MORE_BUTTON_WAS_CLICKED'
// end of MORE BUTTON
